AllCops:
  Exclude:
    - .yardoc/**/*
    - coverage/**/*
    - doc/**/*

  NewCops: enable
  TargetRubyVersion: 3.2

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 12

Performance/RedundantMatch:
  Enabled: false

# Check with yard instead.
Style/Documentation:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
